### ISSUE TITLE
Issues with RetroPie

### ISSUE THREAD

**Issue by Plaputta** [mholgatem/gpioneer#1]
I have some issues getting your script running with RetroPie 3.2.1:
1. The script doesn't work right away because it can't import the RPi.GPIO. I solved this like mentioned here: http://raspberrypi.stackexchange.com/questions/27407/importerror-no-module-named-gpio
   $ sudo apt-get install mercurial
   $ sudo pip install hg+http://hg.code.sf.net/p/raspberry-gpio-python/code#egg=RPi.GPIO
2. After rebooting, the inputs are not recognized, until I connect a USB-Keyboard (I can disconnect it right after it has been recognized), then the GPIO inputs work until the next reboot.

Any ideas?

Thank you!

(Btw, I love your script because it's the only trick I found so far to properly use RetroPie with only 1 Joystick and 3 Buttons by mapping combos. Thank you!)

**Comment by mholgatem** [comment]
Give this a shot:

```
sudo nano /etc/udev/rules.d/10-gpioneer.rules
```

Once the nano text editor loads, copy this single line into the file:

```
SUBSYSTEM=="input", ATTRS{name}=="GPioneer", ENV{ID_INPUT_KEYBOARD}="1"
```

Save the file by pressing Ctrl-O and enter, then press Ctrl-x to exit.  Restart your Raspberry Pi and run retrogame again, now button presses should register in SDL2 applications like the EmulationStation frontend to RetroPie

**Comment by Plaputta** [comment]
That line is already there, your installer worked fine despite the problem with the library..

It's also not EmulationStation related.

Even when in the console, pressing the buttons or joystick does nothing at first - after shortly attaching and detaching a USB keyboard, the buttons and joystick presses print their assigned keys to the console line.

**Comment by mholgatem** [comment]
ok, the only two things that I can think of trying at the moment would be this:

```
nano /etc/modules
```

check to make sure that <b>uinput</b> is listed (add it if it's not)

The other would be 

```
sudo raspi-config
```

choose <b>option 4 - Internationalisation Options</b>, then <b> I3 - Change Keyboard Layout </b>
If it gives you the option, select a default key mapping for your keyboard

I'll ask around to see if anyone has any ideas.

**Comment by Plaputta** [comment]
Hi,

thanks again for your reply!

The uinput was already there but because of that hint I compared the "lsmod" output before and after plugging in the keyboard: the "evdev" module was missing.

I added the "evdev" module to /etc/modules and now the controls work right away without any real keyboard attached!

Thank you very much!

**Comment by mholgatem** [comment]
Awesome! I'll add that to the install script then. Glad we got it working!
