### ISSUE TITLE
Testing unit is not working?

### ISSUE THREAD

**Issue by boquetipo** [mholgatem/gpioneer#10]
Hi. I configure gpioneer for a GBZ project with just a few buttons, just to test.
When I type "sudo python gpioneer/GPioneer.py", and press the configured buttons, nothing happens.
If I press Ctrl+C, it shows up the expected "Kaaaaahhn!"
What am I doing wrong?
Thanks.

**Comment by mholgatem** [comment]
Did you run the configuration utility first? If not, you can run it with 
`sudo python gpioneer/GPioneer.py -c`

**Comment by mholgatem** [comment]
Also, if you plan to use a GPIO connected screen, you are going to want to use
`sudo python gpioneer/GPioneer.py --pins 3,5,7,18` 

3,5,7,18 being a comma-separated list of the pin positions that you want to use

**Comment by boquetipo** [comment]
Yeah, I run the configuration in the first place. The script showed the message the configuration saved correctly.
I don't use a GPIO screen, so all the pins are free for GPIOneer.

I think I'll try to make a new retropie installation and configure GPIOneer from the begining.

**Comment by boquetipo** [comment]
Hi again.
I did a new retropie and GPIOneer installations. After the "Saving configuration... Finished", I run the test and every time a push a key/button, it shows up the text "^[[A".
Is that correct?

**Comment by mholgatem** [comment]
yes, that means that it is working. You need to configure it inside of retropie still though, just like any other controller. 

https://github.com/RetroPie/RetroPie-Setup/wiki/Controller-Configuration

Retropie will see it as a keyboard
