### ISSUE TITLE
Will this work on retrorangepi ?

### ISSUE THREAD

**Issue by PaddleStroke** [mholgatem/gpioneer#11]
Hi,
I was wondering if it would work on orange pi with retrorangepi as well?

I would like to have such PCB : http://gerblook.org/image/jfnptPNHwWvm8oYp3N9gxa/top.png 
to work from GPIO of orange pi.

If you can help or tell me how  I can adapt the drivers to have it working it would be really awesome :)

**Comment by mholgatem** [comment]
unfortunately no, it won't work as is. It relies on the **RPi.gpio python module**, which does not work on the orange pi. 
 **_-but-_**
There is a supposed 'drop in replacement' called [OPi.gpio](https://opi-gpio.readthedocs.io/en/latest/api-documentation.html). If it truly is a drop in replacement, then it should be pretty easy to get it working on the orange pi. 

- First, you will need to make sure that it is installed for your python library. (hint: sudo pip install --upgrade OPi.GPIO)
- Then you will need to replace the import command (line 14 in GPioneer.py) with `import OPi.GPIO as GPIO`

In theory, that should get it working. I'm not sure if the included installer will run properly or not.

**Comment by PaddleStroke** [comment]
Thanks for your explanations!

If I understand correctly the python module is interfacing the configuration of GPIO and writing the driver? 
If so, then can we go without the python module and write directly a driver? If I already know what GPIO will be used?

Sorry if it is a noob question I am discovering linux still.

Could you please explain me how your code works globally? The main steps that the software is going trough. A kind of block diagram so I can understand the global logic that I am missing.

**Comment by PaddleStroke** [comment]
Thanks for your explanations!

If I understand correctly the python code is interfacing the configuration of GPIO and writing the driver?
If so, then can we go without the python module and write directly a driver? If I already know what GPIO will be used?

Sorry if it is a noob question I am discovering linux still.

Could you please explain me how your code works globally? The main steps that the software is going trough. A kind of block diagram so I can understand the global logic that I am missing.

**Comment by mholgatem** [comment]
You can write a program in a different language that will read the state of the gpio pins. You can check out Adafruit's Retrogame utility (written in C).

Basically the program works like this. After running the config, the program builds a database containing gpio pin numbers mapped to keyboard keys. 

when you run the program:

1. it loads the database and adds an event to each pin
2. when the pin's state changes (ie - a button is pressed/released), the event fires
3. depending on the event type, a keyboard event will be fired (key press, key hold, key release)

That's it in a nutshell.
