### ISSUE TITLE
How can i use 27. and 28. Pins as input

### ISSUE THREAD

**Issue by xemre89** [mholgatem/gpioneer#13]
Hi i like your code and thank you for sharing. All gpio pins are busy can i use 27 And 28 I2C Pins as input. Sorry about bad english. Thanks for helping.

**Comment by mholgatem** [comment]
in theory you can, though I've never tried. It would be depend if the python library RPi.GPIO supports it. I can't find the source code for it right now though. If you want to give it a shot, do so at your own risk. you can either manually add the buttons through the web interface or you can can run through the setup again, but use the pins flag, like this
```
gpioneer --configure --pins 3,5,7,11,13,15,19,21,23,27,29,31,33,35,37,8,10,12,16,18,22,24,26,28,32,36,38,40
```
