### ISSUE TITLE
Can't configure controller to EmulationStation

### ISSUE THREAD

**Issue by Suwive** [mholgatem/gpioneer#14]
Hi, also thank you, it seems to work very smoothly and I was able to get it up and running without any difficulty

I'm testing input with a single button (to make sure it works before I buy 12 to make a controller) and was able to successfully configure it in the GPioneer config. However, when I type 'gpionext start' and go back into emulation station, I can't configure the input as a controller.

Any ideas? Thank you very much.

**Comment by mholgatem** [comment]
If I remember correctly, emulation station doesn't recognize any controller that doesn't have at least a directional + 2 buttons. I could be mistaken, but I would test that out. If your setup gives you easy access to  the gpio, I would grab a female to female jumper wire. Plug one end onto a ground gpio pin, then move the other around to different pins to simulate pressing buttons for up/down/etc...

**Comment by Suwive** [comment]
Oh my gosh it worked thank you :)

**Comment by Suwive** [comment]
Oh my gosh it works thank you :)

**Comment by mholgatem** [comment]
yeah, no problem. Let me know how your project turns out! I always like to see what people do!

**Comment by mholgatem** [comment]
btw, gpioneer is deprecated in favor of [GPIOnext](https://github.com/mholgatem/GPIOnext).

If GPioneer works for you, then by all means use it, but GPIOnext is a little more feature rich.
