### ISSUE TITLE
Searching the rc.local entry

### ISSUE THREAD

**Issue by hoever** [mholgatem/gpioneer#15]
Hi,

first of all big thanks for your work.

You wrote in readme:

Advanced configuration
/etc/rc.local has been modified to auto run GPioneer, add any of these flags to modify the runtime settings

If I open /etc/rc.local the file is untouched. I want to try some of the advanced configuration options but I can't find the file, where I have to edit it.

GreetZ
Nils

**Comment by mholgatem** [comment]
sorry, that's old. the rc.local method has been deprecated in favor of creating gpioneer as a service:

> /lib/systemd/system/gpioneer.service

After you make the changes that you want, you need to reload the service. 

```
sudo systemctl stop gpioneer
sudo systemctl daemon-reload
sudo systemctl start gpioneer
```

I really recommend using [GPIOnext](https://github.com/mholgatem/GPIOnext) over GPioneer though.
