### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by JCiszSi** [mholgatem/gpioneer#3]
Hi mholgatem,

under which license do you released the gpioneer software?

**Comment by mholgatem** [comment]
I updated it. It's the **MIT license**. You are free to use/distribute this in anyway that you want (including commercially). It's not required, but it would also be nice if you drop me a line to let me know how the software is being used (I just like to see what people come up with).

**Comment by JCiszSi** [comment]
Thank you for your fast answer :)

Our project isn't completely finished yet, but I'll show up, when we'll be ready
