### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by TheEngler** [mholgatem/gpioneer#6]
I'm a noob to Linux.  I installed the RetroPie 4.2 image and then installed GPioneer on a Pi 3.  The setup configuration right after running was good, the web interface even nicer. 

1. The text after configuration said to use the pipeline character for combo  keys.  The web interface did not like and wanted commas.

2. The text after configuration said to run:  sudo python GPioneer.py -c  which did not work.  I then discovered the web interface.

3. I tried deleting one or two of the default entries via the web interface and it was throwing error.

4. When the Pi boots up, I still get 'No Gamepads Detected'.  I had initially tried Adafruit's Retrogame and had the same issue.  What am I doing wrong here?

-Thanks-

**Comment by TheEngler** [comment]
From one of the closed issues I see issue #2 is a result of the path.  You should put an additional line in the installer to indicate 'cd ~/gpioneer' must be issued first.

**Comment by mholgatem** [comment]
Thanks for the input. 

1 -> I used to use the pipe character initially but then switch to comma separation. I just updated the README file.

3 -> Can you tell me what error you are getting and I'll look into it.

4 -> Gpioneer and retrogame register themselves as keyboards, thus the "No Gamepads Detected". Just press and hold a button while using either utility and it will register that you are configuring a keyboard. Then configuration proceeds as normal.

On a side note, I am getting ready to rewrite the GPioneer code. Part of that rewrite will give you the ability to register it as either a keyboard or a gamepad.

**Comment by TheEngler** [comment]
Thanks for the reply.  For #2 I was referring to:

![capture1](https://cloud.githubusercontent.com/assets/24848723/25363856/e85f9882-292b-11e7-9f65-5fbdbd0c07ce.png)

For #3, I wiped my setup to re-create.  I wrote RetroPie 4.2 then GPioneer.  I allowed it to run configuration and then forced a setup to go through all.  The then entered the web configuration over my network and attempted to delete the last entry.  I got:

![capture2](https://cloud.githubusercontent.com/assets/24848723/25363895/379b5f94-292c-11e7-82ce-048499021a35.png)

For #4 - thanks for the heads up.

That brings up three additional questions:

Q1: Where does the configuration get stored?

Q2: Can there be multiple combo entries?

Q3: Any idea when the re-write wil start and how big an effort it is?

Thanks for the prompt reply!

**Comment by mholgatem** [comment]
hmm.. I'm not able to reproduce that error. I have tried every combo of configuration and deletion that I can come up with. My guess would be that it is  an error with the latest release of Jinja2 (the library that handles the templates). Try this at the command prompt:

> sudo pip uninstall Jinja2
> sudo pip install -I Jinja2==2.8

That will get you to a version of Jinja that has been officially tested.

1. The configuration is stored in an sqlite database in /home/pi/gpioneer/web-frontend/config.db
2. yes, You can do something like this: 

> pin 3 -> key_Q
> pin 5 -> key_W
> pin 7 -> key_E
> pin 3, 5 -> key_R
> pin 3, 7 -> key_T
> pin 5, 7 -> key_Y

3. I am currently working on a series of other projects but my current projection to begin the rewrite is May 1st. It should only take me 2 days to do the rewrite. 

Let me know how it goes with the Jinja thing.

**Comment by TheEngler** [comment]
Uninstalled and loaded Jinja 2.8 as you indicated - still had the same issue.


As to Q1 - since it is SQLite, I guess I cannot easily edit.  If I come up with a configuration and want to duplicate, I assume I can simply copy this file from one Pi to another?

As to Q2 - that is cool since Retrogame only allowed one combination.

As to Q3 - very cool.  Looking forward to the rewrite!

**Comment by TheEngler** [comment]
When I tried, it was on the last entry (Pi_Button 6).  I just tried it again and I am able to delete the first several entries without a problem.  When I get to 'Pi_Button 2', the sheet hits the fan.

**Comment by mholgatem** [comment]
ok, I was finally able to get the problem to manifest itself. I fixed it. To update, just do this:

> cd ~/gpioneer
> git pull

it should be working now.

**Comment by TheEngler** [comment]
Started with a fresh install and everything now works great.  I look forward to your rewrite - thanks for all the help!

**Comment by mholgatem** [comment]
yep. no problemo!
