### ISSUE TITLE
Web server issues.

### ISSUE THREAD

**Issue by JarradFairborn** [mholgatem/gpioneer#8]
I have been successful installing gpioneer and mapping the buttons with the console configuration.  The web interface doesn't allow me to make any changes other than deleting records. If I click on edit record or create entry I get a page displaying:

jinja2.exceptions.TemplateAssertionError
TemplateAssertionError: no test named 'equalto'

I have tried removing gpioneer and re-installing

I also tried:
sudo pip uninstall Jinja2 #this complained it belonged to system

And:
sudo pip install -I Jinja2==2.8 #this installed without error

This system is a raspberry pi 3 running RASPBIAN JESSIE WITH PIXEL

Please let me know if you know what is causing this error. If not is there a another way to map button combinations.

Thank you for your work on this. It is working great for my project otherwise.

Jarrad

**Comment by mholgatem** [comment]
can you give me the exact error that it gave when trying `sudo pip uninstall Jinja2`? 
Without any extra info, my guess would be that it was installed using `apt-get` by some other application.
you should be able to remove it using:
`sudo apt-get remove python-jinja2`

That TemplateAssertionError that you are getting started popping up in Jinja2.9. Running 2.8 has always worked for me in the past. I am currently rewriting all of GPioneer, including the web interface and I plan to tackle this matter when I do.

**Comment by JarradFairborn** [comment]
sudo apt-get remove python-jinja2

Worked great thanks.

**Comment by mholgatem** [comment]
Great! Glad it worked, otherwise I was out of ideas!
