### ISSUE TITLE
No sound after install

### ISSUE THREAD

**Issue by AssoMania** [mholgatem/gpioneer#9]
Hello there,

I'm running a Raspbian + Kodi + EmulationStation.

Your script looks the best to me as it is working on everything compare to Retrogame which is not working in Kodi.
I install Gpioneer, configure everything. Works great. Problem is that since I installed everything I don't have sound anymore. And I don't get where it's coming from. It was working before the installation tho'. In raspbian it's of course unmute, sound to the max.
Any tips ?
I'm running a Pi zero W

**Comment by mholgatem** [comment]
what is your hardware setup? are you providing your audio/video through gpio or mini-hdmi?

**Comment by AssoMania** [comment]
EDIT : It actually work again. Didn't change anything. Just switched off the console... Sorry for that man...
Thanks for the quick answer anyway

**Comment by mholgatem** [comment]
if it's in a psp console, then I would assume that you have the screen/speakers connected to the gpio. So most likely what is happening is that gpioneer is taking control of the gpio pins that are required for your audio. Luckily, I included a command line argument  that you can use. 
you need to do this:

`sudo nano /lib/systemd/system/gpioneer.service`

change line 7 from this:
`ExecStart=/usr/bin/python -u GPioneer.py`
to this:
`ExecStart=/usr/bin/python -u GPioneer.py --pins "3,5,7,11,13,15,19,21,23,29,31,35,37,10,16,18,22,24,26,32,36,38,40"`
(*note - The whole part above should all be one line)

save and exit, then reboot your system and you should be able to get audio now
